### PR TITLE
push notification 

### PR DESCRIPTION
**Pull request by shreya024**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/soumik2012/Chathub/blob/master/CONTRIBUTING.md)?

Yes

### Description

subscribe and unsubscribe a user for push messaging and display a notification using Firebase Cloud Messaging

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.

## Related Issues or Pull Requests

#15

### CODE REVIEW

**Comment by shreya024** [comment]
@soumikbaithalu Kindly review my PR

**Comment by heet-kumar** [comment]
@shreya024 share here some of the Screenshots of the output or short video.

**Comment by shreya024** [comment]
> @shreya024 share here some of the Screenshots of the output or short video.

notification

**Comment by shreya024** [comment]
Could not upload a video because notifications are not getting recorded when I do screen recording

**Review by heet-kumar — APPROVED** [review]
@shreya024 Great work done

**Comment by heet-kumar** [comment]
From my side its well and good to go @soumikbaithalu once review from your side if any changes are required then mention once here.

**Review by soumikbaithalu — CHANGES_REQUESTED** [review]
I have run your program but it is `failed to complied` please what bug the code and fix it.
image

image

**Comment by shreya024** [comment]
> I have run your program but it is `failed to complied` please what bug the code and fix it. image
> 
> image

emoji-mart was not used by me and I am not getting an error on my IDE.However,since this PR was made days ago, I will take a pull and try to fix the bug.

**Comment by shreya024** [comment]
image
Not getting any errors.
Maybe you are missing some package

**Pull request closed without merging**
