### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Aniket-508**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/soumik2012/Chathub/blob/master/CONTRIBUTING.md)?

Yes

### Description

Updated readme file as mentioned by mentor.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.

## Related Issues or Pull Requests
#45

### CODE REVIEW

**Comment by Aniket-508** [comment]
@soumikbaithalu Please have a look at this!

**Comment by soumikbaithalu** [comment]
@Aniket-508 you have committed in the master branch checkout from the master branch and make another PR.

**Comment by Aniket-508** [comment]
@soumikbaithalu It will take time for this minor change, can't you directly merge this please!

**Review by soumikbaithalu — APPROVED** [review]
LGTM 💯

**Pull request merged**
