### PR TITLE
fix errors

### PR DESCRIPTION
**Pull request by TheBotlyNoob**
again

### CODE REVIEW

**Comment by TheBotlyNoob** [comment]
wait

**Comment by soumikbaithalu** [comment]
image
still not deploy

**Review by soumikbaithalu — CHANGES_REQUESTED** [review]
@TheBotlyNoob Resolve the merge conflict error

**Comment by TheBotlyNoob** [comment]
@soumik2012 I can't, you have to.

**Comment by TheBotlyNoob** [comment]
and the errors have been fixed.

**Comment by soumikbaithalu** [comment]
@TheBotlyNoob Thank you so much for helping

**Comment by TheBotlyNoob** [comment]
np

**Pull request merged**
