### PR TITLE
Adding push notification on chat messages

### PR DESCRIPTION
**Pull request by shreya024**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/soumik2012/Chathub/blob/master/CONTRIBUTING.md)?

Yes

### Description

subscribe and unsubscribe a user for push messaging and display a notification using Firebase Cloud Messaging

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.

## Related Issues or Pull Requests

#15

### CODE REVIEW

**Review by soumikbaithalu — COMMENTED** [review]
@shreya024 you have committed in the master branch also vercel failed to load the website

**Comment by shreya024** [comment]
Since there is a service worker that's why vercel failed. And let me know which branch you want me to make the commit to?

**Comment by soumikbaithalu** [comment]
@shreya024 Make a another PR and checkout from master branch

**Comment by shreya024** [comment]
> @shreya024 Make a another PR and checkout from master branch

I have made another PR

**Pull request closed without merging**
