### PR TITLE
Position scroll bar to the bottom always

### LINKED ISSUE #36: Position Scroll
It would be nice, if we can showing the latest message than showing the first message every time.

### PR DESCRIPTION
**Pull request by Prathap-P**
Solves issue #36

### CODE REVIEW

**Comment by Prathap-P** [comment]
I can see that 1 check is failed. But I can also see that this branch has no conflicts with the base branch. What are the chances we have now.

**Comment by soumik2012** [comment]
LGTM 💯

**Comment by soumikbaithalu** [comment]
@Prathap-P  LGTM 💯

**Review by soumikbaithalu — COMMENTED** [review]
Good Work 👍🏻

**Pull request merged**
